services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.11.4
    volumes:
      - ~/.aws:/root/.aws:ro 
      - ./:/workdir
    working_dir: "/workdir"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION